#include <gtk/gtk.h>

char *css=
"  @define-color BACKGROUND rgb(9%,9%,10%);\n"
"  @define-color SURFACE rgb(16%,16%,19%);\n"
"  @define-color SURFACE_HOVER rgb(24%,24%,28%);\n"
"  @define-color BORDER rgb(28%,28%,33%);\n"
"  @define-color OFF_WHITE rgb(89%,89%,91%);\n"
"  @define-color DARK_TEXT rgb(66%,66%,72%);\n"
"  @define-color ACCENT_A rgb(50%,80%,84%);\n"
"  @define-color ACCENT_B rgb(93%,62%,50%);\n"
"  @define-color ACCENT_ON rgb(58%,46%,72%);\n"
"  @define-color WARNING rgb(85%,27%,27%);\n"
"  @define-color INFO_ON rgb(15%,58%,60%);\n"
"  #receiver-window {\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #vfo-a-text {\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    font-family: Noto Sans;\n"
"    color: @ACCENT_A;\n"
"    }\n"
"  #frequency-a-text {\n"
"    font-family: Noto Mono;\n"
"    font-size: 32px;\n"
"    color: @ACCENT_A;\n"
"    }\n"
"  #vfo-b-text {\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: @ACCENT_B;\n"
"    }\n"
"  #frequency-b-text {\n"
"    font-family: Noto Mono;\n"
"    font-size: 21px;\n"
"    color: @ACCENT_B;\n"
"    }\n"
"  #toolbar-button {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 4px;\n"
"    padding-right: 10px;\n"
"    padding-bottom: 4px;\n"
"    padding-left: 10px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 22px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #toolbar-button:hover {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 4px;\n"
"    padding-right: 10px;\n"
"    padding-bottom: 4px;\n"
"    padding-left: 10px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 22px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE_HOVER;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #toolbar-button:disabled {\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: rgb(36%,36%,40%);\n"
"    opacity: 0.55;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-button {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-button:hover {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE_HOVER;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-toggle {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-toggle:hover {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE_HOVER;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-mode-filter-button {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @ACCENT_ON;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-toggle:checked {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @ACCENT_ON;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  .label {\n"
"    border-width: 0px;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    }\n"
"  #warning-label {\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    color: @WARNING;\n"
"    }\n"
"  #info-button {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 0px;\n"
"    padding-right: 0px;\n"
"    padding-bottom: 0px;\n"
"    padding-left: 0px;\n"
"    font-size: small;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 0px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #rit-value {\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #xit-value {\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #afgain-text {\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #afgain-scale trough {\n"
"    background-color: @SURFACE;\n"
"    border-color: @BORDER;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    box-shadow: none;\n"
"    }\n"
"  #afgain-scale trough block.filled {\n"
"    border-color: @ACCENT_A;\n"
"    color: @ACCENT_A;\n"
"    }\n"
"  #squelch-text {\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #squelch-scale trough {\n"
"    background-color: @SURFACE;\n"
"    border-color: @BORDER;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    box-shadow: none;\n"
"    }\n"
"  #squelch-scale trough block.filled {\n"
"    border-color: @ACCENT_A;\n"
"    color: @ACCENT_A;\n"
"    }\n"
"  #agcgain-text {\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #agcgain-scale trough {\n"
"    background-color: @SURFACE;\n"
"    border-color: @BORDER;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    box-shadow: none;\n"
"    }\n"
"  #agcgain-scale trough block.filled  {\n"
"    background-color: @ACCENT_B;\n"
"    border-color: @OFF_WHITE;\n"
"  }\n"
"  #info-warning {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #info-warning:checked {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @WARNING;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #info-button {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #info-button:hover {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE_HOVER;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #info-button:checked {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 3px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 3px;\n"
"    padding-left: 6px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 16px;\n"
"    background-image: none;\n"
"    background-color: @INFO_ON;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #transmit-warning {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 4px;\n"
"    padding-right: 10px;\n"
"    padding-bottom: 4px;\n"
"    padding-left: 10px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 22px;\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @DARK_TEXT;\n"
"    box-shadow: none;\n"
"    }\n"
"  #transmit-warning:checked {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    border-width: 1px;\n"
"    padding-top: 4px;\n"
"    padding-right: 10px;\n"
"    padding-bottom: 4px;\n"
"    padding-left: 10px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    min-height: 22px;\n"
"    background-image: none;\n"
"    background-color: @WARNING;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-close {\n"
"    border-radius: 4px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: @BORDER;\n"
"    padding-top: 1px;\n"
"    padding-right: 6px;\n"
"    padding-bottom: 1px;\n"
"    padding-left: 6px;\n"
"    margin-top: 4px;\n"
"    margin-right: 4px;\n"
"    margin-bottom: 4px;\n"
"    margin-left: 4px;\n"
"    min-height: 18px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    background-image: none;\n"
"    background-color: @SURFACE_HOVER;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #vfo-close:hover {\n"
"    background-image: none;\n"
"    background-color: @WARNING;\n"
"    color: @OFF_WHITE;\n"
"    border-color: @WARNING;\n"
"    box-shadow: none;\n"
"    }\n"
"  #toolbar-button:checked {\n"
"    border-radius: 5px;\n"
"    border-style: none;\n"
"    padding-top: 4px;\n"
"    padding-right: 10px;\n"
"    padding-bottom: 4px;\n"
"    padding-left: 10px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    min-height: 22px;\n"
"    background-image: none;\n"
"    background-color: @ACCENT_ON;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: none;\n"
"    }\n"
"  #bottom-bar {\n"
"    background-color: @BACKGROUND;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 14px;\n"
"    padding-left: 16px;\n"
"    padding-right: 16px;\n"
"    }\n"
"  #section-label {\n"
"    font-family: Noto Sans;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    color: rgb(46%,46%,52%);\n"
"    margin-left: 2px;\n"
"    }\n"
"  #bar-rail {\n"
"    background-color: transparent;\n"
"    background-image: linear-gradient(to bottom, alpha(@BORDER,0.0), @BORDER 18%, @BORDER 82%, alpha(@BORDER,0.0));\n"
"    min-width: 1px;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"    margin-left: 14px;\n"
"    margin-right: 14px;\n"
"    border-style: none;\n"
"    }\n"
"  #bar-rail-accent {\n"
"    background-color: transparent;\n"
"    background-image: linear-gradient(to bottom, alpha(@ACCENT_A,0.0), alpha(@ACCENT_A,0.55) 15%, alpha(@ACCENT_A,0.55) 85%, alpha(@ACCENT_A,0.0));\n"
"    min-width: 2px;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"    margin-left: 14px;\n"
"    margin-right: 14px;\n"
"    border-style: none;\n"
"    }\n"
"  #rx-bottom-sep {\n"
"    margin-top: 3px;\n"
"    margin-bottom: 3px;\n"
"    }\n"
"  #rx-bottom-sep separator {\n"
"    background-image: none;\n"
"    background-color: alpha(@ACCENT_A,0.30);\n"
"    min-height: 1px;\n"
"    }\n"
"  paned {\n"
"    background-color: @BACKGROUND;\n"
"    }\n"
"  paned > separator {\n"
"    background-image: none;\n"
"    background-color: @BACKGROUND;\n"
"    min-width: 2px;\n"
"    min-height: 2px;\n"
"    }\n"
/* ---- Configuration dialog: flat-dark, scoped under #config-dialog so the ----
   ---- main window (which paints its own named widgets) is never touched. ---- */
"  #config-dialog {\n"
"    background-color: @BACKGROUND;\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #config-dialog decoration {\n"
"    background-color: @BACKGROUND;\n"
"    }\n"
"  #config-dialog stacksidebar {\n"
"    background-color: @BACKGROUND;\n"
"    border-right: 1px solid @BORDER;\n"
"    }\n"
"  #config-dialog stacksidebar list {\n"
"    background-color: @BACKGROUND;\n"
"    padding: 6px;\n"
"    }\n"
"  #config-dialog stacksidebar row {\n"
"    background-image: none;\n"
"    background-color: transparent;\n"
"    color: @DARK_TEXT;\n"
"    padding: 6px 14px;\n"
"    border-radius: 5px;\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    }\n"
"  #config-dialog stacksidebar row:hover {\n"
"    background-color: @SURFACE;\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #config-dialog stacksidebar row:selected {\n"
"    background-color: @SURFACE;\n"
"    color: @OFF_WHITE;\n"
"    box-shadow: inset 3px 0 @ACCENT_A;\n"
"    }\n"
"  #config-dialog stacksidebar row label {\n"
"    color: inherit;\n"
"    }\n"
"  #config-stack {\n"
"    background-color: @BACKGROUND;\n"
"    padding: 12px 16px;\n"
"    }\n"
"  #config-dialog frame {\n"
"    border-style: none;\n"
"    }\n"
"  #config-dialog frame > border {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: @BORDER;\n"
"    border-radius: 6px;\n"
"    }\n"
"  #config-dialog frame > label {\n"
"    color: @ACCENT_A;\n"
"    font-family: Noto Sans;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    margin-bottom: 4px;\n"
"    }\n"
"  #config-dialog label {\n"
"    color: @OFF_WHITE;\n"
"    font-family: Noto Sans;\n"
"    font-size: 12px;\n"
"    }\n"
"  #config-dialog button {\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @OFF_WHITE;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: @BORDER;\n"
"    border-radius: 5px;\n"
"    box-shadow: none;\n"
"    padding: 4px 10px;\n"
"    }\n"
"  #config-dialog button:hover {\n"
"    background-color: @SURFACE_HOVER;\n"
"    }\n"
"  #config-dialog button:checked, #config-dialog button:active {\n"
"    background-color: @ACCENT_ON;\n"
"    color: @OFF_WHITE;\n"
"    border-color: @ACCENT_ON;\n"
"    }\n"
"  #config-dialog entry, #config-dialog spinbutton {\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @OFF_WHITE;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: @BORDER;\n"
"    border-radius: 5px;\n"
"    box-shadow: none;\n"
"    }\n"
"  #config-dialog spinbutton button {\n"
"    border-radius: 0px;\n"
"    border-style: none;\n"
"    }\n"
"  #config-dialog combobox button {\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    color: @OFF_WHITE;\n"
"    border-color: @BORDER;\n"
"    }\n"
"  #config-dialog checkbutton, #config-dialog radiobutton {\n"
"    color: @OFF_WHITE;\n"
"    }\n"
"  #config-dialog check, #config-dialog radio {\n"
"    background-image: none;\n"
"    background-color: @SURFACE;\n"
"    border-color: @BORDER;\n"
"    }\n"
"  #config-dialog check:checked, #config-dialog radio:checked {\n"
"    background-image: none;\n"
"    background-color: @ACCENT_A;\n"
"    border-color: @ACCENT_A;\n"
"    color: @BACKGROUND;\n"
"    }\n"
"  #config-dialog scale trough {\n"
"    background-color: @SURFACE;\n"
"    border-color: @BORDER;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    box-shadow: none;\n"
"    }\n"
"  #config-dialog scale highlight {\n"
"    background-color: @ACCENT_A;\n"
"    border-radius: 4px;\n"
"    }\n"
"  #config-dialog scale slider {\n"
"    background-color: @OFF_WHITE;\n"
"    border-radius: 50%;\n"
"    }\n"
"  #config-dialog separator {\n"
"    background-color: @BORDER;\n"
"    }\n"
;

void load_css() {
  GtkCssProvider *provider;
  GdkDisplay *display;
  GdkScreen *screen;

  g_print("%s\n",__FUNCTION__);

  // Ask GTK for the dark variant of the active theme so stock widgets that we
  // do not paint ourselves (combobox popups, menus, scrollbars, tooltips,
  // spin buttons in the config dialog) default to dark instead of light.
  g_object_set(gtk_settings_get_default(),
               "gtk-application-prefer-dark-theme",TRUE,NULL);

  provider = gtk_css_provider_new ();
  display = gdk_display_get_default ();
  screen = gdk_display_get_default_screen (display);
  gtk_style_context_add_provider_for_screen (screen,
                                             GTK_STYLE_PROVIDER(provider),
                                             GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);

  gtk_css_provider_load_from_data(provider, css, -1, NULL);
  g_object_unref (provider);
}
